<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-TPFSN6P1" failures="1" tests="1" name="TC01_Test" time="7.797" errors="0" timestamp="2021-09-28T21:49:06 IST">
  <testcase classname="Reporter_Example_Word.TC01_Test" name="Test1" time="7.766">
    <failure type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException" message="Fail to save: an error occurs while saving the package : null">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:595)
at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1539)
at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:227)
at Reporter_Example_Word.ImageAttachmentInDocument1.WordOutput_File(ImageAttachmentInDocument1.java:114)
at Reporter_Example_Word.TC01_Test.Test1(TC01_Test.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
Caused by: java.lang.NullPointerException
at java.base/java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:84)
at java.base/java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:142)
at java.base/java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:134)
at java.base/java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:120)
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:529)
... 32 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
</testsuite> <!-- TC01_Test -->
